# Site settings
title: Ruilin's notes
email: zruilin@126.com
description: "For technology exchange and study."
logo_location: "https://avatars2.githubusercontent.com/u/6614628?s=400&u=cbf14bb602dfc15dc34d1817c488e3353244ad68&v=4"

#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--more-->

#show the jumbotron header on index page
show_blog_header: true
